// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: demo.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoServiceClient interface {
	GetDemo(ctx context.Context, in *DemoRequst, opts ...grpc.CallOption) (*DemoResponse, error)
	GetCStream(ctx context.Context, opts ...grpc.CallOption) (DemoService_GetCStreamClient, error)
	GetSStream(ctx context.Context, in *DemoRequst, opts ...grpc.CallOption) (DemoService_GetSStreamClient, error)
	GetBiStream(ctx context.Context, opts ...grpc.CallOption) (DemoService_GetBiStreamClient, error)
}

type demoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoServiceClient(cc grpc.ClientConnInterface) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) GetDemo(ctx context.Context, in *DemoRequst, opts ...grpc.CallOption) (*DemoResponse, error) {
	out := new(DemoResponse)
	err := c.cc.Invoke(ctx, "/DemoService/GetDemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoServiceClient) GetCStream(ctx context.Context, opts ...grpc.CallOption) (DemoService_GetCStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[0], "/DemoService/GetCStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &demoServiceGetCStreamClient{stream}
	return x, nil
}

type DemoService_GetCStreamClient interface {
	Send(*DemoRequst) error
	CloseAndRecv() (*DemoResponse, error)
	grpc.ClientStream
}

type demoServiceGetCStreamClient struct {
	grpc.ClientStream
}

func (x *demoServiceGetCStreamClient) Send(m *DemoRequst) error {
	return x.ClientStream.SendMsg(m)
}

func (x *demoServiceGetCStreamClient) CloseAndRecv() (*DemoResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DemoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *demoServiceClient) GetSStream(ctx context.Context, in *DemoRequst, opts ...grpc.CallOption) (DemoService_GetSStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[1], "/DemoService/GetSStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &demoServiceGetSStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DemoService_GetSStreamClient interface {
	Recv() (*DemoResponse, error)
	grpc.ClientStream
}

type demoServiceGetSStreamClient struct {
	grpc.ClientStream
}

func (x *demoServiceGetSStreamClient) Recv() (*DemoResponse, error) {
	m := new(DemoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *demoServiceClient) GetBiStream(ctx context.Context, opts ...grpc.CallOption) (DemoService_GetBiStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[2], "/DemoService/GetBiStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &demoServiceGetBiStreamClient{stream}
	return x, nil
}

type DemoService_GetBiStreamClient interface {
	Send(*DemoRequst) error
	Recv() (*DemoResponse, error)
	grpc.ClientStream
}

type demoServiceGetBiStreamClient struct {
	grpc.ClientStream
}

func (x *demoServiceGetBiStreamClient) Send(m *DemoRequst) error {
	return x.ClientStream.SendMsg(m)
}

func (x *demoServiceGetBiStreamClient) Recv() (*DemoResponse, error) {
	m := new(DemoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoServiceServer is the server API for DemoService service.
// All implementations must embed UnimplementedDemoServiceServer
// for forward compatibility
type DemoServiceServer interface {
	GetDemo(context.Context, *DemoRequst) (*DemoResponse, error)
	GetCStream(DemoService_GetCStreamServer) error
	GetSStream(*DemoRequst, DemoService_GetSStreamServer) error
	GetBiStream(DemoService_GetBiStreamServer) error
	mustEmbedUnimplementedDemoServiceServer()
}

// UnimplementedDemoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDemoServiceServer struct {
}

func (UnimplementedDemoServiceServer) GetDemo(context.Context, *DemoRequst) (*DemoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDemo not implemented")
}
func (UnimplementedDemoServiceServer) GetCStream(DemoService_GetCStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCStream not implemented")
}
func (UnimplementedDemoServiceServer) GetSStream(*DemoRequst, DemoService_GetSStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSStream not implemented")
}
func (UnimplementedDemoServiceServer) GetBiStream(DemoService_GetBiStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBiStream not implemented")
}
func (UnimplementedDemoServiceServer) mustEmbedUnimplementedDemoServiceServer() {}

// UnsafeDemoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoServiceServer will
// result in compilation errors.
type UnsafeDemoServiceServer interface {
	mustEmbedUnimplementedDemoServiceServer()
}

func RegisterDemoServiceServer(s grpc.ServiceRegistrar, srv DemoServiceServer) {
	s.RegisterService(&DemoService_ServiceDesc, srv)
}

func _DemoService_GetDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).GetDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DemoService/GetDemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).GetDemo(ctx, req.(*DemoRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoService_GetCStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).GetCStream(&demoServiceGetCStreamServer{stream})
}

type DemoService_GetCStreamServer interface {
	SendAndClose(*DemoResponse) error
	Recv() (*DemoRequst, error)
	grpc.ServerStream
}

type demoServiceGetCStreamServer struct {
	grpc.ServerStream
}

func (x *demoServiceGetCStreamServer) SendAndClose(m *DemoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *demoServiceGetCStreamServer) Recv() (*DemoRequst, error) {
	m := new(DemoRequst)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DemoService_GetSStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DemoRequst)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoServiceServer).GetSStream(m, &demoServiceGetSStreamServer{stream})
}

type DemoService_GetSStreamServer interface {
	Send(*DemoResponse) error
	grpc.ServerStream
}

type demoServiceGetSStreamServer struct {
	grpc.ServerStream
}

func (x *demoServiceGetSStreamServer) Send(m *DemoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DemoService_GetBiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).GetBiStream(&demoServiceGetBiStreamServer{stream})
}

type DemoService_GetBiStreamServer interface {
	Send(*DemoResponse) error
	Recv() (*DemoRequst, error)
	grpc.ServerStream
}

type demoServiceGetBiStreamServer struct {
	grpc.ServerStream
}

func (x *demoServiceGetBiStreamServer) Send(m *DemoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *demoServiceGetBiStreamServer) Recv() (*DemoRequst, error) {
	m := new(DemoRequst)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoService_ServiceDesc is the grpc.ServiceDesc for DemoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDemo",
			Handler:    _DemoService_GetDemo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCStream",
			Handler:       _DemoService_GetCStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSStream",
			Handler:       _DemoService_GetSStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBiStream",
			Handler:       _DemoService_GetBiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "demo.proto",
}
